/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CashierRouteImport } from './routes/_cashier'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated.transactions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated.payments'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedChildrenRouteImport } from './routes/_authenticated.children'
import { Route as CashierCashierIndexRouteImport } from './routes/_cashier.cashier.index'
import { Route as AuthenticatedReceiptsIndexRouteImport } from './routes/_authenticated.receipts.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as CashierCashierStudentsRouteImport } from './routes/_cashier.cashier.students'
import { Route as CashierCashierProfileRouteImport } from './routes/_cashier.cashier.profile'
import { Route as CashierCashierNotificationsRouteImport } from './routes/_cashier.cashier.notifications'
import { Route as CashierCashierCollectionsRouteImport } from './routes/_cashier.cashier.collections'
import { Route as AuthenticatedReportsPaymentsRouteImport } from './routes/_authenticated.reports.payments'
import { Route as AuthenticatedReceiptsIdRouteImport } from './routes/_authenticated.receipts.$id'
import { Route as AdminAdminStudentsOverviewRouteImport } from './routes/_admin.admin.students-overview'
import { Route as AdminAdminStudentsRouteImport } from './routes/_admin.admin.students'
import { Route as AdminAdminProfileRouteImport } from './routes/_admin.admin.profile'
import { Route as AdminAdminParentsRouteImport } from './routes/_admin.admin.parents'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin.admin.notifications'
import { Route as AdminAdminFeesRouteImport } from './routes/_admin.admin.fees'
import { Route as AdminAdminCollectionsRouteImport } from './routes/_admin.admin.collections'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin.admin.users.index'
import { Route as AdminAdminSchoolsIndexRouteImport } from './routes/_admin.admin.schools.index'
import { Route as AdminAdminUsersNewRouteImport } from './routes/_admin.admin.users.new'
import { Route as AdminAdminUsersIdRouteImport } from './routes/_admin.admin.users.$id'
import { Route as AdminAdminStudentsNewRouteImport } from './routes/_admin.admin.students.new'
import { Route as AdminAdminSchoolsNewRouteImport } from './routes/_admin.admin.schools.new'
import { Route as AdminAdminSchoolsIdRouteImport } from './routes/_admin.admin.schools.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/_cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChildrenRoute = AuthenticatedChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CashierCashierIndexRoute = CashierCashierIndexRouteImport.update({
  id: '/cashier/',
  path: '/cashier/',
  getParentRoute: () => CashierRoute,
} as any)
const AuthenticatedReceiptsIndexRoute =
  AuthenticatedReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const CashierCashierStudentsRoute = CashierCashierStudentsRouteImport.update({
  id: '/cashier/students',
  path: '/cashier/students',
  getParentRoute: () => CashierRoute,
} as any)
const CashierCashierProfileRoute = CashierCashierProfileRouteImport.update({
  id: '/cashier/profile',
  path: '/cashier/profile',
  getParentRoute: () => CashierRoute,
} as any)
const CashierCashierNotificationsRoute =
  CashierCashierNotificationsRouteImport.update({
    id: '/cashier/notifications',
    path: '/cashier/notifications',
    getParentRoute: () => CashierRoute,
  } as any)
const CashierCashierCollectionsRoute =
  CashierCashierCollectionsRouteImport.update({
    id: '/cashier/collections',
    path: '/cashier/collections',
    getParentRoute: () => CashierRoute,
  } as any)
const AuthenticatedReportsPaymentsRoute =
  AuthenticatedReportsPaymentsRouteImport.update({
    id: '/reports/payments',
    path: '/reports/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsIdRoute = AuthenticatedReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminStudentsOverviewRoute =
  AdminAdminStudentsOverviewRouteImport.update({
    id: '/admin/students-overview',
    path: '/admin/students-overview',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminStudentsRoute = AdminAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProfileRoute = AdminAdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminParentsRoute = AdminAdminParentsRouteImport.update({
  id: '/admin/parents',
  path: '/admin/parents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFeesRoute = AdminAdminFeesRouteImport.update({
  id: '/admin/fees',
  path: '/admin/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCollectionsRoute = AdminAdminCollectionsRouteImport.update({
  id: '/admin/collections',
  path: '/admin/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSchoolsIndexRoute = AdminAdminSchoolsIndexRouteImport.update({
  id: '/admin/schools/',
  path: '/admin/schools/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersNewRoute = AdminAdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersIdRoute = AdminAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminStudentsNewRoute = AdminAdminStudentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminStudentsRoute,
} as any)
const AdminAdminSchoolsNewRoute = AdminAdminSchoolsNewRouteImport.update({
  id: '/admin/schools/new',
  path: '/admin/schools/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSchoolsIdRoute = AdminAdminSchoolsIdRouteImport.update({
  id: '/admin/schools/$id',
  path: '/admin/schools/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/admin/collections': typeof AdminAdminCollectionsRoute
  '/admin/fees': typeof AdminAdminFeesRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/parents': typeof AdminAdminParentsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/students': typeof AdminAdminStudentsRouteWithChildren
  '/admin/students-overview': typeof AdminAdminStudentsOverviewRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/reports/payments': typeof AuthenticatedReportsPaymentsRoute
  '/cashier/collections': typeof CashierCashierCollectionsRoute
  '/cashier/notifications': typeof CashierCashierNotificationsRoute
  '/cashier/profile': typeof CashierCashierProfileRoute
  '/cashier/students': typeof CashierCashierStudentsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/cashier/': typeof CashierCashierIndexRoute
  '/admin/schools/$id': typeof AdminAdminSchoolsIdRoute
  '/admin/schools/new': typeof AdminAdminSchoolsNewRoute
  '/admin/students/new': typeof AdminAdminStudentsNewRoute
  '/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/admin/users/new': typeof AdminAdminUsersNewRoute
  '/admin/schools/': typeof AdminAdminSchoolsIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/admin/collections': typeof AdminAdminCollectionsRoute
  '/admin/fees': typeof AdminAdminFeesRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/parents': typeof AdminAdminParentsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/students': typeof AdminAdminStudentsRouteWithChildren
  '/admin/students-overview': typeof AdminAdminStudentsOverviewRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/reports/payments': typeof AuthenticatedReportsPaymentsRoute
  '/cashier/collections': typeof CashierCashierCollectionsRoute
  '/cashier/notifications': typeof CashierCashierNotificationsRoute
  '/cashier/profile': typeof CashierCashierProfileRoute
  '/cashier/students': typeof CashierCashierStudentsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/receipts': typeof AuthenticatedReceiptsIndexRoute
  '/cashier': typeof CashierCashierIndexRoute
  '/admin/schools/$id': typeof AdminAdminSchoolsIdRoute
  '/admin/schools/new': typeof AdminAdminSchoolsNewRoute
  '/admin/students/new': typeof AdminAdminStudentsNewRoute
  '/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/admin/users/new': typeof AdminAdminUsersNewRoute
  '/admin/schools': typeof AdminAdminSchoolsIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_cashier': typeof CashierRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/children': typeof AuthenticatedChildrenRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_admin/admin/collections': typeof AdminAdminCollectionsRoute
  '/_admin/admin/fees': typeof AdminAdminFeesRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/parents': typeof AdminAdminParentsRoute
  '/_admin/admin/profile': typeof AdminAdminProfileRoute
  '/_admin/admin/students': typeof AdminAdminStudentsRouteWithChildren
  '/_admin/admin/students-overview': typeof AdminAdminStudentsOverviewRoute
  '/_authenticated/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/_authenticated/reports/payments': typeof AuthenticatedReportsPaymentsRoute
  '/_cashier/cashier/collections': typeof CashierCashierCollectionsRoute
  '/_cashier/cashier/notifications': typeof CashierCashierNotificationsRoute
  '/_cashier/cashier/profile': typeof CashierCashierProfileRoute
  '/_cashier/cashier/students': typeof CashierCashierStudentsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/_cashier/cashier/': typeof CashierCashierIndexRoute
  '/_admin/admin/schools/$id': typeof AdminAdminSchoolsIdRoute
  '/_admin/admin/schools/new': typeof AdminAdminSchoolsNewRoute
  '/_admin/admin/students/new': typeof AdminAdminStudentsNewRoute
  '/_admin/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/_admin/admin/users/new': typeof AdminAdminUsersNewRoute
  '/_admin/admin/schools/': typeof AdminAdminSchoolsIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/children'
    | '/home'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/transactions'
    | '/admin/collections'
    | '/admin/fees'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/profile'
    | '/admin/students'
    | '/admin/students-overview'
    | '/receipts/$id'
    | '/reports/payments'
    | '/cashier/collections'
    | '/cashier/notifications'
    | '/cashier/profile'
    | '/cashier/students'
    | '/admin/'
    | '/receipts/'
    | '/cashier/'
    | '/admin/schools/$id'
    | '/admin/schools/new'
    | '/admin/students/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/schools/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/children'
    | '/home'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/transactions'
    | '/admin/collections'
    | '/admin/fees'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/profile'
    | '/admin/students'
    | '/admin/students-overview'
    | '/receipts/$id'
    | '/reports/payments'
    | '/cashier/collections'
    | '/cashier/notifications'
    | '/cashier/profile'
    | '/cashier/students'
    | '/admin'
    | '/receipts'
    | '/cashier'
    | '/admin/schools/$id'
    | '/admin/schools/new'
    | '/admin/students/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/schools'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_cashier'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/children'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/transactions'
    | '/_admin/admin/collections'
    | '/_admin/admin/fees'
    | '/_admin/admin/notifications'
    | '/_admin/admin/parents'
    | '/_admin/admin/profile'
    | '/_admin/admin/students'
    | '/_admin/admin/students-overview'
    | '/_authenticated/receipts/$id'
    | '/_authenticated/reports/payments'
    | '/_cashier/cashier/collections'
    | '/_cashier/cashier/notifications'
    | '/_cashier/cashier/profile'
    | '/_cashier/cashier/students'
    | '/_admin/admin/'
    | '/_authenticated/receipts/'
    | '/_cashier/cashier/'
    | '/_admin/admin/schools/$id'
    | '/_admin/admin/schools/new'
    | '/_admin/admin/students/new'
    | '/_admin/admin/users/$id'
    | '/_admin/admin/users/new'
    | '/_admin/admin/schools/'
    | '/_admin/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CashierRoute: typeof CashierRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cashier': {
      id: '/_cashier'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/children': {
      id: '/_authenticated/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AuthenticatedChildrenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_cashier/cashier/': {
      id: '/_cashier/cashier/'
      path: '/cashier'
      fullPath: '/cashier/'
      preLoaderRoute: typeof CashierCashierIndexRouteImport
      parentRoute: typeof CashierRoute
    }
    '/_authenticated/receipts/': {
      id: '/_authenticated/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AuthenticatedReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_cashier/cashier/students': {
      id: '/_cashier/cashier/students'
      path: '/cashier/students'
      fullPath: '/cashier/students'
      preLoaderRoute: typeof CashierCashierStudentsRouteImport
      parentRoute: typeof CashierRoute
    }
    '/_cashier/cashier/profile': {
      id: '/_cashier/cashier/profile'
      path: '/cashier/profile'
      fullPath: '/cashier/profile'
      preLoaderRoute: typeof CashierCashierProfileRouteImport
      parentRoute: typeof CashierRoute
    }
    '/_cashier/cashier/notifications': {
      id: '/_cashier/cashier/notifications'
      path: '/cashier/notifications'
      fullPath: '/cashier/notifications'
      preLoaderRoute: typeof CashierCashierNotificationsRouteImport
      parentRoute: typeof CashierRoute
    }
    '/_cashier/cashier/collections': {
      id: '/_cashier/cashier/collections'
      path: '/cashier/collections'
      fullPath: '/cashier/collections'
      preLoaderRoute: typeof CashierCashierCollectionsRouteImport
      parentRoute: typeof CashierRoute
    }
    '/_authenticated/reports/payments': {
      id: '/_authenticated/reports/payments'
      path: '/reports/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof AuthenticatedReportsPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts/$id': {
      id: '/_authenticated/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof AuthenticatedReceiptsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/students-overview': {
      id: '/_admin/admin/students-overview'
      path: '/admin/students-overview'
      fullPath: '/admin/students-overview'
      preLoaderRoute: typeof AdminAdminStudentsOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/students': {
      id: '/_admin/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/profile': {
      id: '/_admin/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminAdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/parents': {
      id: '/_admin/admin/parents'
      path: '/admin/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AdminAdminParentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/fees': {
      id: '/_admin/admin/fees'
      path: '/admin/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminAdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/collections': {
      id: '/_admin/admin/collections'
      path: '/admin/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminAdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/schools/': {
      id: '/_admin/admin/schools/'
      path: '/admin/schools'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AdminAdminSchoolsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/new': {
      id: '/_admin/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminAdminUsersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/$id': {
      id: '/_admin/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminAdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/students/new': {
      id: '/_admin/admin/students/new'
      path: '/new'
      fullPath: '/admin/students/new'
      preLoaderRoute: typeof AdminAdminStudentsNewRouteImport
      parentRoute: typeof AdminAdminStudentsRoute
    }
    '/_admin/admin/schools/new': {
      id: '/_admin/admin/schools/new'
      path: '/admin/schools/new'
      fullPath: '/admin/schools/new'
      preLoaderRoute: typeof AdminAdminSchoolsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/schools/$id': {
      id: '/_admin/admin/schools/$id'
      path: '/admin/schools/$id'
      fullPath: '/admin/schools/$id'
      preLoaderRoute: typeof AdminAdminSchoolsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminAdminStudentsRouteChildren {
  AdminAdminStudentsNewRoute: typeof AdminAdminStudentsNewRoute
}

const AdminAdminStudentsRouteChildren: AdminAdminStudentsRouteChildren = {
  AdminAdminStudentsNewRoute: AdminAdminStudentsNewRoute,
}

const AdminAdminStudentsRouteWithChildren =
  AdminAdminStudentsRoute._addFileChildren(AdminAdminStudentsRouteChildren)

interface AdminRouteChildren {
  AdminAdminCollectionsRoute: typeof AdminAdminCollectionsRoute
  AdminAdminFeesRoute: typeof AdminAdminFeesRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminParentsRoute: typeof AdminAdminParentsRoute
  AdminAdminProfileRoute: typeof AdminAdminProfileRoute
  AdminAdminStudentsRoute: typeof AdminAdminStudentsRouteWithChildren
  AdminAdminStudentsOverviewRoute: typeof AdminAdminStudentsOverviewRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminSchoolsIdRoute: typeof AdminAdminSchoolsIdRoute
  AdminAdminSchoolsNewRoute: typeof AdminAdminSchoolsNewRoute
  AdminAdminUsersIdRoute: typeof AdminAdminUsersIdRoute
  AdminAdminUsersNewRoute: typeof AdminAdminUsersNewRoute
  AdminAdminSchoolsIndexRoute: typeof AdminAdminSchoolsIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCollectionsRoute: AdminAdminCollectionsRoute,
  AdminAdminFeesRoute: AdminAdminFeesRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminParentsRoute: AdminAdminParentsRoute,
  AdminAdminProfileRoute: AdminAdminProfileRoute,
  AdminAdminStudentsRoute: AdminAdminStudentsRouteWithChildren,
  AdminAdminStudentsOverviewRoute: AdminAdminStudentsOverviewRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminSchoolsIdRoute: AdminAdminSchoolsIdRoute,
  AdminAdminSchoolsNewRoute: AdminAdminSchoolsNewRoute,
  AdminAdminUsersIdRoute: AdminAdminUsersIdRoute,
  AdminAdminUsersNewRoute: AdminAdminUsersNewRoute,
  AdminAdminSchoolsIndexRoute: AdminAdminSchoolsIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChildrenRoute: typeof AuthenticatedChildrenRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedReceiptsIdRoute: typeof AuthenticatedReceiptsIdRoute
  AuthenticatedReportsPaymentsRoute: typeof AuthenticatedReportsPaymentsRoute
  AuthenticatedReceiptsIndexRoute: typeof AuthenticatedReceiptsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChildrenRoute: AuthenticatedChildrenRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedReceiptsIdRoute: AuthenticatedReceiptsIdRoute,
  AuthenticatedReportsPaymentsRoute: AuthenticatedReportsPaymentsRoute,
  AuthenticatedReceiptsIndexRoute: AuthenticatedReceiptsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CashierRouteChildren {
  CashierCashierCollectionsRoute: typeof CashierCashierCollectionsRoute
  CashierCashierNotificationsRoute: typeof CashierCashierNotificationsRoute
  CashierCashierProfileRoute: typeof CashierCashierProfileRoute
  CashierCashierStudentsRoute: typeof CashierCashierStudentsRoute
  CashierCashierIndexRoute: typeof CashierCashierIndexRoute
}

const CashierRouteChildren: CashierRouteChildren = {
  CashierCashierCollectionsRoute: CashierCashierCollectionsRoute,
  CashierCashierNotificationsRoute: CashierCashierNotificationsRoute,
  CashierCashierProfileRoute: CashierCashierProfileRoute,
  CashierCashierStudentsRoute: CashierCashierStudentsRoute,
  CashierCashierIndexRoute: CashierCashierIndexRoute,
}

const CashierRouteWithChildren =
  CashierRoute._addFileChildren(CashierRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CashierRoute: CashierRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
